version: '3.7'
services:
  app:
    build:
      context: ./app
      target: build
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    tty: true
    command: realize start --run --no-config