name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run go mod download
      working-directory: ./app
      run: go mod download

    - name: Install golangci-lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
        sudo mv ./bin/golangci-lint $GOPATH/bin/

    - name: Run golangci-lint
      run: >
        golangci-lint run ./app/... \
          --tests \
          --enable-all \
          --disable gochecknoglobals \
          --disable gochecknoinits

    - name: Run tests
      run: go test -race -v ./app/...